version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      ADB_INSTALL_TIMEOUT: 10
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew clean androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install Android dependencies
          command: |
            sdkmanager "platform-tools"
            sdkmanager "platforms;android-21"
            sdkmanager "platforms;android-22"
            sdkmanager "platforms;android-23"
            sdkmanager "platforms;android-24"
            sdkmanager "platforms;android-25"
            sdkmanager "platforms;android-26"
            sdkmanager "build-tools;27.0.3"
            sdkmanager "extras;android;m2repository"
            sdkmanager "extras;google;m2repository"
            sdkmanager "extras;google;google_play_services"
            sdkmanager "system-images;android-25;default;armeabi-v7a"
      - run:
          name: Setup emulator
          command: echo "no" | avdmanager create avd -n test -k "system-images;android-25;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait for emulator
          command: circle-android wait-for-boot
      - run:
          name: Run UI tests
          command: ./gradlew connectedAndroidTest
      - run:
          name: Build and check
          command: ./gradlew testDebug jacocoTestReport coveralls checkstyle pmd jdepend lintDebug buildDashboard -PpreDexEnable=false -PversionCode=$CIRCLE_BUILD_NUM
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
